#!/usr/bin/env python3
"""Git operations module for Auto Deploy Agent"""

import os
import subprocess
from config import PROJECT_DIR

def check_and_install_git():
    """Check if git is installed, ask to install if not."""
    # Reuse the installation logic from cli_manager
    from core.cli_manager import install_cli
    return install_cli("GitHub Pages")  # Reuse the installation logic

def create_gitignore(project_type):
    """Create a .gitignore file based on the project type."""
    gitignore_path = PROJECT_DIR / ".gitignore"
    
    if gitignore_path.exists():
        print(".gitignore file already exists.")
        return True
    
    print("Creating .gitignore file...")
    
    # Base gitignore content
    gitignore_content = """# Dependencies
node_modules/
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env*

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next/
out/

# Nuxt.js build / generate output
.nuxt
dist/

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public/

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

"""

    # Add Python-specific ignores
    if project_type in ["python-flask"]:
        gitignore_content += """# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
.pybuilder/
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
#   For a library or package, you might want to ignore these files since the code is
#   intended to run in multiple environments; otherwise, check them in:
.python-version

# pipenv
#   According to pypa/pipenv#598, it is recommended to include Pipfile.lock in version control.
#   However, in case of collaboration, if having platform-specific dependencies or dependencies
#   having no cross-platform support, pipenv may install dependencies that don't work, or not
#   install all needed dependencies.
#Pipfile.lock

# poetry
#   Similar to Pipfile.lock, it is generally recommended to include poetry.lock in version control.
#   This is especially recommended for binary packages to ensure reproducibility, and is more
#   commonly ignored for libraries.
#   https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control
#poetry.lock

# pdm
#   Similar to Pipfile.lock, it is generally recommended to include pdm.lock in version control.
#pdm.lock
#   pdm stores project-wide configurations in .pdm.toml, but it is recommended to not include it
#   in version control.
#   https://pdm.fming.dev/#use-with-ide
.pdm.toml

# PEP 582; used by e.g. github.com/David-OConnor/pyflow and github.com/pdm-project/pdm
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# SageMath parsed files
*.sage.py

# Environments
.env/
.venv/
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# pytype static type analyzer
.pytype/

# Cython debug symbols
cython_debug/

# PyCharm
#  JetBrains specific template is maintained in a separate JetBrains.gitignore that can
#  be found at https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
#  and can be added to the global gitignore or merged into this file.  For a more nuclear
#  option (not recommended) you can uncomment the following to ignore the entire idea folder.
#.idea/

"""

    try:
        with open(gitignore_path, "w") as f:
            f.write(gitignore_content)
        print(".gitignore file created successfully!")
        return True
    except Exception as e:
        print(f"Failed to create .gitignore file: {e}")
        return False

def is_git_repo():
    """Check if the current directory is a Git repository."""
    return os.path.exists(".git")

def get_git_remote_url():
    """Get the remote URL of the Git repository if it exists."""
    try:
        result = subprocess.run("git remote get-url origin", capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True, timeout=10)
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except subprocess.TimeoutExpired:
        print("Checking remote repository timed out")
    except Exception as e:
        print(f"Error checking remote repository: {e}")
    return None

def has_uncommitted_changes():
    """Check if there are uncommitted changes in the Git repository."""
    try:
        result = subprocess.run("git status --porcelain", capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True, timeout=10)
        return bool(result.stdout.strip())
    except subprocess.TimeoutExpired:
        print("Checking git status timed out")
        return False
    except Exception as e:
        print(f"Error checking git status: {e}")
        return False

def generate_commit_message():
    """Generate a meaningful commit message using Ollama (with fallback to file-based logic)."""
    try:
        # Get file changes
        result = subprocess.run("git diff --name-only --cached", capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True, timeout=10)
        staged_files = result.stdout.strip().split('\n') if result.stdout.strip() else []
        
        result = subprocess.run("git diff --name-only", capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True, timeout=10)
        unstaged_files = result.stdout.strip().split('\n') if result.stdout.strip() else []
        
        all_files = [f for f in staged_files + unstaged_files if f]
        
        if not all_files:
            return "Update project files"
        
        # Try to use Ollama to generate a smart commit message
        try:
            import ollama
            from config import OLLAMA_MODEL
            
            # Get git diff content to analyze
            diff_result = subprocess.run("git diff --no-color HEAD", capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True, timeout=15)
            diff_content = diff_result.stdout[:2000]  # Limit to first 2000 chars to avoid token overflow
            
            files_list = ", ".join(all_files[:10])  # Show first 10 files
            
            prompt = f"""Analyze these git changes and generate a concise, conventional commit message (format: type: description).
Files changed: {files_list}
{'...' if len(all_files) > 10 else ''}

Diff preview:
{diff_content}

Generate ONE commit message in conventional commit format. Be concise (50 chars max). No extra text."""
            
            response = ollama.chat(
                model=OLLAMA_MODEL,
                messages=[{"role": "user", "content": prompt}],
                options={"timeout": 10}
            )
            
            commit_msg = response["message"]["content"].strip()
            # Ensure it's a valid commit message (remove quotes, extra whitespace)
            commit_msg = commit_msg.replace('"', '').replace("'", '').strip()
            
            if commit_msg and len(commit_msg) > 0 and len(commit_msg) < 200:
                return commit_msg
        except Exception as e:
            # Ollama failed, will use fallback
            pass
        
        # Fallback: Categorize files and generate message
        config_files = [f for f in all_files if any(x in f for x in ['config', '.env', '.json', 'requirements', 'package'])]
        src_files = [f for f in all_files if any(x in f for x in ['src', 'app.py', 'index', '.py', '.js', '.ts'])]
        doc_files = [f for f in all_files if any(x in f for x in ['README', '.md', 'docs'])]
        deploy_files = [f for f in all_files if any(x in f for x in ['vercel', 'netlify', 'deploy'])]
        
        # Generate message based on what changed
        if deploy_files and len(all_files) <= 3:
            return "chore: update deployment configuration"
        elif config_files and src_files:
            return "feat: update application code and configuration"
        elif src_files:
            return f"feat: update application code ({len(src_files)} files)"
        elif config_files:
            return "chore: update configuration files"
        elif doc_files:
            return "docs: update documentation"
        else:
            return f"chore: update project files ({len(all_files)} files)"
    except Exception:
        return "Auto-generated commit"

def git_add_and_commit(commit_message="Initial commit"):
    """Add all files and commit them."""
    try:
        # Check if there are any changes to commit
        if not has_uncommitted_changes():
            print("No changes to commit.")
            return True
            
        print("Adding files to git...")
        subprocess.run("git add .", check=True, shell=True, text=True, encoding="utf-8", errors="replace", timeout=30)
        
        print("Committing changes...")
        # Use subprocess with list arguments to avoid shell injection issues
        subprocess.run(["git", "commit", "-m", commit_message], check=True, text=True, encoding="utf-8", errors="replace", timeout=30)
        return True
    except subprocess.TimeoutExpired:
        print("Git add/commit timed out")
        return False
    except subprocess.CalledProcessError as e:
        # Check if it's a "nothing to commit" error
        if "nothing to commit" in str(e):
            print("No changes to commit.")
            return True
        print(f"Git add/commit failed: {e}")
        return False
    except Exception as e:
        print(f"Git add/commit error: {e}")
        return False

def git_push_to_remote():
    """Push changes to the remote repository."""
    try:
        print("Pushing to remote repository...")
        subprocess.run("git push -u origin main", check=True, shell=True, text=True, encoding="utf-8", errors="replace", timeout=120)
        print("Pushed to remote repository!")
        return True
    except subprocess.TimeoutExpired:
        print("Git push timed out")
        return False
    except subprocess.CalledProcessError as e:
        print(f"Git push failed: {e}")
        return False
    except Exception as e:
        print(f"Git push error: {e}")
        return False

def init_git_repo(auto_init=False):
    """Initialize dir as git repo. If auto_init=True, skip permission prompts."""
    if is_git_repo():
        print("This directory is already a git repository.")
        remote_url = get_git_remote_url()
        if remote_url:
            print(f"Already connected to remote: {remote_url}")
            return True
        else:
            print("No remote repository configured.")
            if auto_init:
                # In auto-init mode, we should still prompt for remote URL setup
                repo_url = input("Enter your remote Git repository URL (e.g., https://github.com/user/repo.git) or leave blank to skip: ").strip()
                if repo_url:
                    try:
                        subprocess.run(f"git remote add origin {repo_url}", check=True, shell=True, text=True, encoding="utf-8", errors="replace", timeout=30)
                        subprocess.run("git branch -M main", check=True, shell=True, text=True, encoding="utf-8", errors="replace", timeout=30)
                        print(f"✓ Remote repository configured: {repo_url}")
                        return True
                    except subprocess.TimeoutExpired:
                        print("Git remote setup timed out")
                        return False
                    except subprocess.CalledProcessError as e:
                        print(f"Git remote setup failed: {e}")
                        return False
                    except Exception as e:
                        print(f"Git remote setup error: {e}")
                        return False
                else:
                    print("Skipped remote repository setup.")
                    return True
            else:
                return True
    
    if not auto_init:
        permission = input("Do you want me to initialize a git repository for this project? (y/n): ")
        if permission.lower() != 'y':
            return False
    else:
        print("Initializing git repository automatically...")

    try:
        print("Initializing git repo...")
        subprocess.run("git init", check=True, shell=True, text=True, encoding="utf-8", errors="replace", timeout=30)
        
        # Create .gitignore file
        files = [f.name for f in PROJECT_DIR.iterdir() if f.is_file()]
        project_type = "unknown"
        if "package.json" in files:
            project_type = "node"
        elif "requirements.txt" in files:
            project_type = "python-flask"
        elif "index.html" in files:
            project_type = "static"
            
        create_gitignore(project_type)
        
        # Auto-commit files with generated message
        commit_msg = "chore: initial project setup"
        if not git_add_and_commit(commit_msg):
            print("Failed to commit changes.")
            return False
            
        return True
    except subprocess.TimeoutExpired:
        print("Git operation timed out")
        return False
    except subprocess.CalledProcessError as e:
        print(f"Git operation failed: {e}")
        return False
    except Exception as e:
        print(f"Git init failed: {e}")
        return False