#!/usr/bin/env python3
"""Git operations module for Auto Deploy Agent"""

import os
import subprocess
from config import PROJECT_DIR

def check_and_install_git():
    """Check if git is installed, ask to install if not."""
    # Reuse the installation logic from cli_manager
    from core.cli_manager import install_cli
    return install_cli("GitHub Pages")  # Reuse the installation logic

def create_gitignore(project_type):
    """Create a .gitignore file based on the project type."""
    gitignore_path = PROJECT_DIR / ".gitignore"
    
    if gitignore_path.exists():
        print("✅ .gitignore file already exists.")
        return True
    
    print("📄 Creating .gitignore file...")
    
    # Base gitignore content
    gitignore_content = """# Dependencies
node_modules/
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env*

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next/
out/

# Nuxt.js build / generate output
.nuxt
dist/

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public/

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

"""

    # Add Python-specific ignores
    if project_type in ["python-flask"]:
        gitignore_content += """# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
.pybuilder/
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
#   For a library or package, you might want to ignore these files since the code is
#   intended to run in multiple environments; otherwise, check them in:
.python-version

# pipenv
#   According to pypa/pipenv#598, it is recommended to include Pipfile.lock in version control.
#   However, in case of collaboration, if having platform-specific dependencies or dependencies
#   having no cross-platform support, pipenv may install dependencies that don't work, or not
#   install all needed dependencies.
#Pipfile.lock

# poetry
#   Similar to Pipfile.lock, it is generally recommended to include poetry.lock in version control.
#   This is especially recommended for binary packages to ensure reproducibility, and is more
#   commonly ignored for libraries.
#   https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control
#poetry.lock

# pdm
#   Similar to Pipfile.lock, it is generally recommended to include pdm.lock in version control.
#pdm.lock
#   pdm stores project-wide configurations in .pdm.toml, but it is recommended to not include it
#   in version control.
#   https://pdm.fming.dev/#use-with-ide
.pdm.toml

# PEP 582; used by e.g. github.com/David-OConnor/pyflow and github.com/pdm-project/pdm
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# SageMath parsed files
*.sage.py

# Environments
.env/
.venv/
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# pytype static type analyzer
.pytype/

# Cython debug symbols
cython_debug/

# PyCharm
#  JetBrains specific template is maintained in a separate JetBrains.gitignore that can
#  be found at https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
#  and can be added to the global gitignore or merged into this file.  For a more nuclear
#  option (not recommended) you can uncomment the following to ignore the entire idea folder.
#.idea/

"""

    try:
        with open(gitignore_path, "w") as f:
            f.write(gitignore_content)
        print("✅ .gitignore file created successfully!")
        return True
    except Exception as e:
        print(f"❌ Failed to create .gitignore file: {e}")
        return False

def init_git_repo():
    """Initialize dir as git repo with user permission, and connect to remote."""
    if os.path.exists(".git"):
        print("✅ This directory is already a git repository.")
        # Check if remote exists
        try:
            result = subprocess.run("git remote get-url origin", capture_output=True, text=True, shell=True, timeout=10)
            if result.returncode == 0 and result.stdout.strip():
                print(f"🔗 Already connected to remote: {result.stdout.strip()}")
                return True
        except subprocess.TimeoutExpired:
            print("⚠️ Checking remote repository timed out")
        except Exception as e:
            print(f"⚠️ Error checking remote repository: {e}")

    permission = input("Do you want me to initialize a git repository for this project? (y/n): ")
    if permission.lower() != 'y':
        return False

    try:
        print("🔧 Initializing git repo...")
        subprocess.run("git init", check=True, shell=True, timeout=30)
        
        # Create .gitignore file
        # We'll determine project type by checking existing files
        files = [f.name for f in PROJECT_DIR.iterdir() if f.is_file()]
        project_type = "unknown"
        if "package.json" in files:
            project_type = "node"
        elif "requirements.txt" in files:
            project_type = "python-flask"
        elif "index.html" in files:
            project_type = "static"
            
        create_gitignore(project_type)
        
        subprocess.run("git add .", check=True, shell=True, timeout=30)
        commit_msg = input("Enter commit message (default: 'Initial commit'): ") or "Initial commit"
        subprocess.run(f"git commit -m '{commit_msg}'", check=True, shell=True, timeout=30)

        # Ask for remote repository URL
        repo_url = input("Enter your remote Git repository URL (e.g., https://github.com/user/repo.git) or leave blank to skip: ").strip()
        if repo_url:
            subprocess.run(f"git remote add origin {repo_url}", check=True, shell=True, timeout=30)
            subprocess.run("git branch -M main", check=True, shell=True, timeout=30)
            push_permission = input("Do you want to push to the remote repository now? (y/n): ")
            if push_permission.lower() == 'y':
                print("🚀 Pushing to remote repository...")
                subprocess.run("git push -u origin main", check=True, shell=True, timeout=120)
                print("✅ Pushed to remote repository!")
        else:
            print("ℹ️  Skipped remote repository setup. You can add it later with 'git remote add origin <url>'")
            
        return True
    except subprocess.TimeoutExpired:
        print("❌ Git operation timed out")
        return False
    except subprocess.CalledProcessError as e:
        print(f"❌ Git operation failed: {e}")
        return False
    except Exception as e:
        print(f"❌ Git init failed: {e}")
        return False